DROP TABLE IF EXISTS ID_SEQUENCE;
CREATE TABLE ID_SEQUENCE
(
    colname SERIAL
);

DROP TABLE IF EXISTS ACCOUNT;
CREATE TABLE ACCOUNT
(
    ID        SERIAL PRIMARY KEY,
    USERNAME  VARCHAR,
    EMAIL     VARCHAR,
    FIRSTNAME VARCHAR,
    LASTNAME  VARCHAR
);

INSERT INTO ACCOUNT (USERNAME, EMAIL, FIRSTNAME, LASTNAME)
VALUES ('alalstjr', 'alalstjr@naver.com', 'kim', 'minseok');